# -*- coding: utf-8 -*-
"""YOLO_Training.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NadpIjFY5ZI8GaiMMWVshURkYps-fXXX
"""

!git clone https://github.com/pedropro/TACO



!pip3 install -r TACO/requirements.txt

!pip3 install git+https://github.com/philferriere/cocoapi.git#subdirectory=PythonAPI

# Commented out IPython magic to ensure Python compatibility.
# %cd TACO

!python3 download.py

!python3 download.py --dataset_path ./data/annotations_unofficial.json

# Commented out IPython magic to ensure Python compatibility.
# %cd detector



!python3 split_dataset.py --dataset_dir ../data

# Commented out IPython magic to ensure Python compatibility.
# %cd ..

!git clone https://github.com/ultralytics/yolov5

# Commented out IPython magic to ensure Python compatibility.


# %cd yolov5 
!pip install -r requirements.txt

import torch

model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

model

!python train.py --img 320 --batch 16 --epochs 500 --data dataset.yaml --weights yolov5s.pt --workers 2



from google.colab import drive
drive.mount('/content/drive')